### ISSUE TITLE
Workflow Login -> Logout -> Login is broken

### ISSUE THREAD

**Issue by mam10eks** [disraptor/disraptor#11]
When we disable disraptor, it is possible to do "login -> logout -> login", but when disraptor is active, only "login -> logout" is working, and the new login does not work (loading symbol is shown, but nothing happens)

**Comment by BastianGrahm** [comment]
Since it even occurs if the route used to mimic this behavior is not set by Disraptor the solution is related to modification of scripts most likely.
To resolve I will check the differences that appear when Disraptor is used versus when it is not.

**Comment by BastianGrahm** [comment]
Fixed with #11
