### ISSUE TITLE
Disraptor shows me only blank pages on mobile devices

### ISSUE THREAD

**Issue by mam10eks** [disraptor/disraptor#14]
On my android phone and also in the dev-tools in a browser (when selecting a mobile device) it shows me only a blank page, e.g. on a task page:

![Screenshot_20210116_134310](https://user-images.githubusercontent.com/10050886/104812347-cea40780-5801-11eb-8773-8372ffabcf1e.png)

**Comment by BastianGrahm** [comment]
It's pretty confusing why this happens. All the DOM is loaded correctly and shown for a split second when loading a page. Right after that it goes blank. DOM still there though. All the clickable elements and text boxes can also still be used.

ALSO this only affects the task page as it seems. As I keep on navigating all the sites seem to work but the task page.

**Comment by mam10eks** [comment]
I think I found the problem. The code had a check for `transition.intent.url === this.defaultHomePath`, and as a result, disraptor did not recognize URLs as `/latest/` or `/latest?mobile_view=1` as the default home path, so those pages were rendered twice. The commit above should fix the issue.

**Comment by mam10eks** [comment]
This works now, awesome :)
