### ISSUE TITLE
Handle status 302 responses

### ISSUE THREAD

**Issue by BastianGrahm** [disraptor/disraptor#17]
Only status code 200, 303 and 404 are really handled by Disraptor right now.

Since 302 and 303 are pretty similar and 302 is also often used to redirect we should handle it too.

Therefore the 303 handling can probably be used, since they basically work the same. 
This can be found here: https://github.com/disraptor/disraptor/blob/25139d44878f825b23d03cac7295df01cde565d7/app/controllers/proxy_controller.rb#L31

**Comment by potthast** [comment]
Since it's a switch statement, this should be an easy fix.

**Comment by BastianGrahm** [comment]
I checked and 303 is effectively the same as 302 in our use case. So I will use the current 303 block for both.

**Comment by BastianGrahm** [comment]
Solved at https://github.com/disraptor/disraptor/commit/3a3379e0b9a921b527ac58edaeaee82541d43cd8.
