### ISSUE TITLE
Links from /latest to / don’t work with a Disraptor root route

### ISSUE THREAD

**Issue by kleinfreund** [disraptor/disraptor#2]
**Steps to reproduce**:

1. Configure a root route with Disraptor.
2. Navigate to the Discourse forum: [localhost:3000/latest](http://localhost:3000/latest).
3. Click the logo (it has a link target of `/`).

**Expected behavior**:

A navigation to the Disraptor root route is performed.

**Actual behavior**:

Nothing happens.

**Reason**:

(See issue #3)

**Comment by kleinfreund** [comment]
Analysis:

- Discourse handles requests to `/` like requests to `/latest` in Ember. In fact, Ember never gets to see a request to `/`.
- For this reason, Disraptor sets up its own Ember route for the path `/latest` so it can hijack the mechanism of loading the default forum page and load a Disraptor document instead.
- Both these points together imply that when requesting `/`, the Ember route that will be active is `disraptor-proxy.latest`.
- If the is a link to `/latest` on the root route page, no Ember transition will be triggered since from the perspective of Ember, the pages with the paths `/` and `/latest` are the same. Ember thinks a transition is unnecessary because the user is already on the intended page. This is not Embers mistake, but due to the oddity of Discourse treating requests to `/` like requests to `/latest` internally.

I have no soltution for this problem right now.

We could take all links to `/` or `/latest` and intercept their click events with JavaScript. Then, maybe we can somehow trigger the transition anyway. This would be a terrible hack.

The core problem really is our inability to setup a true root route with Disraptor that is not redirected to `/latest` internally before we can do anything about it.

**Comment by potthast** [comment]
So it is not possible to set up two independent Controllers, one for /, one for /latest, and have them to the same thing?

**Comment by kleinfreund** [comment]
On the client side (Ember), I cannot use a route for `/` at all since the client side never gets to see requests to `/`:

1. User requests `/`.
2. Inside Discourse’s Rails application (server side), the request is handled by `ListController#latest`. The same happens when a user requests `/latest`.
3. Inside Discourse’s Ember application (client side), the request is handled by the route `discovery.latest`. From Ember’s perspective, the route `discovery.latest` was triggered by a request to the URL `/latest` no matter if the requested URL was `/` or `/latest` initially.

Now if a user is already on a page represented by the route `discovery.latest`, requesting a URL that Ember maps to the same router will not trigger a navigation (in Ember land, it would be called a transition). In other words: For Ember, `/` and `/latest` are the same and they do the same thing so it does not transition because the user is already where they want to be. From Ember’s perspective that’s totally correct. Even from Discourse’s perspective, that’s appropriate behavior since both `/` and `/latest` do represent the same thing.

I will try to investigate whether we can make the default forum page available on a different path. Then, we can maybe avoid this mess.

**Comment by kleinfreund** [comment]
A possible workaround for this issue could work similar as the hack that was added in https://github.com/disraptor/disraptor/commit/f7ab5694ba2ba3c7f78b2bd87090b6943d26a7ce to fix #3.

However, since we’re not in a Disraptor context on the forum page, we have no direct way to run a script. We could make use of Discourse’s theming capabilities and inject a script there.
