### ISSUE TITLE
Gray overlay / unusable site in mobile browsers

### ISSUE THREAD

**Issue by potthast** [disraptor/disraptor#7]
In mobile Chrome and Firefox on Android, there is a gray overlay that cannot be dismissed and that renders the page non-interactive.

**Comment by kleinfreund** [comment]
This is likely a regression in the latest version of Discourse which I upgraded to on the Tira production test site. I can’t reproduce it in my development environment which I didn’t upgrade.

**Comment by potthast** [comment]
I'm not sure what to make of this explanation: What can we do to ensure the problem remains solved?

**Comment by kleinfreund** [comment]
We currently run a Discourse version based on the latest commit from the Discourse repo. This is prone to bugs. On an actual production environment, we would not do this.

**Comment by kleinfreund** [comment]
I re-wrote the navigation theme component to make more use of Discourse’s internals. This is now using Discourse logic for most aspects and there is a chance that I can make it fully dependant on Discourse logic. With that, this issue is resolved, too.
